"""initial migration

Revision ID: 32644b215fb7
Revises: 49f87170801f
Create Date: 2016-09-03 10:59:35.070000

"""

# revision identifiers, used by Alembic.
revision = '32644b215fb7'
down_revision = '49f87170801f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('buy', sa.String(length=10), nullable=True))
    op.drop_column('users', 'buy')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('buy', mysql.VARCHAR(length=10), nullable=True))
    op.drop_column('item', 'buy')
    ### end Alembic commands ###
