"""initial migration

Revision ID: 3d5e0b17a0ee
Revises: 32644b215fb7
Create Date: 2016-09-03 17:09:53.393000

"""

# revision identifiers, used by Alembic.
revision = '3d5e0b17a0ee'
down_revision = '32644b215fb7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('buyer', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'buyer')
    ### end Alembic commands ###
