"""initial migration

Revision ID: 3fefc0faac3d
Revises: 2cc224ceb9fb
Create Date: 2016-08-31 13:23:31.226000

"""

# revision identifiers, used by Alembic.
revision = '3fefc0faac3d'
down_revision = '2cc224ceb9fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tel', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tel')
    ### end Alembic commands ###
