"""initial migration

Revision ID: 465f59125a21
Revises: None
Create Date: 2016-08-29 14:04:56.627000

"""

# revision identifiers, used by Alembic.
revision = '465f59125a21'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.alter_column(u'item', 'detal',
               existing_type=mysql.CHAR(length=140),
               nullable=True)
    op.alter_column(u'item', 'img1',
               existing_type=mysql.CHAR(length=80),
               nullable=True)
    op.alter_column(u'item', 'img2',
               existing_type=mysql.CHAR(length=80),
               nullable=True)
    op.alter_column(u'item', 'img3',
               existing_type=mysql.CHAR(length=80),
               nullable=True)
    op.alter_column(u'item', 'name',
               existing_type=mysql.CHAR(length=64),
               nullable=True)
    op.alter_column(u'item', 'title',
               existing_type=mysql.CHAR(length=20),
               nullable=True)
    op.create_unique_constraint(None, 'item', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item')
    op.alter_column(u'item', 'title',
               existing_type=mysql.CHAR(length=20),
               nullable=False)
    op.alter_column(u'item', 'name',
               existing_type=mysql.CHAR(length=64),
               nullable=False)
    op.alter_column(u'item', 'img3',
               existing_type=mysql.CHAR(length=80),
               nullable=False)
    op.alter_column(u'item', 'img2',
               existing_type=mysql.CHAR(length=80),
               nullable=False)
    op.alter_column(u'item', 'img1',
               existing_type=mysql.CHAR(length=80),
               nullable=False)
    op.alter_column(u'item', 'detal',
               existing_type=mysql.CHAR(length=140),
               nullable=False)
    op.drop_index('ix_users_username', 'users')
    op.drop_table('users')
    op.drop_table('roles')
    ### end Alembic commands ###
