"""initial migration

Revision ID: 4fc5eb589d36
Revises: 3d5e0b17a0ee
Create Date: 2016-09-05 13:58:18.521000

"""

# revision identifiers, used by Alembic.
revision = '4fc5eb589d36'
down_revision = '3d5e0b17a0ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
