"""initial migration

Revision ID: cd49b9cac34
Revises: 16e602d29dcd
Create Date: 2016-08-30 12:43:42.102000

"""

# revision identifiers, used by Alembic.
revision = 'cd49b9cac34'
down_revision = '16e602d29dcd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
